# Exported from Render on 2024-04-30T16:09:03Z
databases:
- name: watch-list
  databaseName: watch_list_0b20
  user: hiroya
  plan: free
  region: singapore
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "15"

# Exported from Render on 2024-04-30T17:16:29Z
services:
- type: web
  name: watch-list
  runtime: ruby
  repo: https://github.com/hiroya210/rails-watch-list
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    value: 2
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
