# Exported from Render on 2024-04-30T16:09:03Z
databases:
- name: watch-list
  databaseName: watch_list_0b20
  user: hiroya
  plan: free
  region: singapore
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "15"
version: "1"

services:
  - type: web
    name: watch-list
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: watch-list
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
